#!/bin/sh

### BEGIN INIT INFO
# Provides:       stalker-web
# Required-Start: $local_fs $syslog
# Required-Stop:  $local_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Gunicorn processes for stalker-web
### END INIT INFO

USER=www-data
RUNDIR=/var/run/stalker
PIDFILE=$RUNDIR/stalker-web.pid
DAEMON=/usr/bin/stalker-web
NAME=stalker-web
DESC=stalker-web
STALKERCONF=/etc/stalker/stalkerweb.cfg
GUNICORN_WORKERS=8
GUNICORN_PID=$RUNDIR/gunicorn-stalkerweb.pid
RETVAL=0

# source function library
. /lib/lsb/init-functions

start()
{
    echo -n "Starting $NAME ... "
    chgrp www-data /var/run/stalker
    chmod g+w /var/run/stalker
    # export PYTHONPATH=$CONFDIR;
    # cd $CONFDIR/$NAME;
    su $USER -c "/usr/bin/stalker-web --conf=$STALKERCONF -P $PIDFILE -G -w $GUNICORN_WORKERS  >/dev/null"
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "Failed"
    fi
}

stop()
{
    echo -n "Stopping $NAME"
    ppid=`cat $PIDFILE`
    child_procs=`ps --no-headers -o  pid --ppid $ppid`
    kill -9 $ppid
    if [ $? -eq 0 ]; then
        echo " parent process ... OK"
        rm $PIDFILE
    else
        echo " parent process ... Failed"
    fi
    echo -n "Killing $NAME child processes ("$child_procs") ... "
    kill -9 $child_procs
    if [ $? -eq 0 ]; then
        echo "Done"
    else
        echo "Failed"
    fi
}

reload()
{
    echo "Reloading $NAME:"
    if [ -f $PIDFILE ]; then
        kill -HUP `cat $PIDFILE` && echo "OK" || echo "failed";
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop && start
        ;;
    reload)
        reload
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        RETVAL=1
esac
exit $RETVAL
